spring:
  datasource:
    maximum-pool-size: 30
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    table: grapql_demo_schema_version
    baseline-on-migrate: true
    baseline-version: 0
    repair: true

jwt:
  secret: ${jwt_key:dr@ma&is&ever7h1ng}
  issuer: ${jwt_issuer:grapql-server}
  passwordStrength: -1

